# Note:  This publishes the package based of the tag version. The tag version should be in the format vx.x.x
# However, the version of the published package will be taken from the package.json file. It is best practice
# to keep the version in the package.json file and the tag version the same.
name: Publish Node.js Package

on:
    push:
        tags:
            - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
    build:
        name: Build and Publish
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
            - uses: actions/checkout@v4
            - uses: pnpm/action-setup@v4
              name: Install pnpm
              with:
                  version: 9
                  run_install: false
            - uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: "pnpm"
                  registry-url: https://npm.pkg.github.com/
            - name: Install dependencies
              run: pnpm install
            - name: Run tests
              run: pnpm test
            - name: Build
              run: pnpm build
            - run: pnpm publish --no-git-checks
              env:
                  NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
